name: phage-pipeline
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # QC & Trimming
  - fastplong
  # Assembly & Polishing
  - flye
  - medaka
  # Assembly QC
  - checkv
  - viralverify
  # Annotation
  - pharokka
  - phold
  # - phynteny
  # Reporting & utilities
  - multiqc
  - wget
